update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.AbstractDomainObject',NAME='edu.wustl.clinportal.domain.AbstractDomainObject'   where DESCRIPTION='edu.wustl.catissuecore.domain.AbstractDomainObject';
update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.Address',NAME='edu.wustl.clinportal.domain.Address'  where DESCRIPTION='edu.wustl.catissuecore.domain.Address';
update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.ClinicalStudyRegistration',NAME='edu.wustl.clinportal.domain.ClinicalStudyRegistration' where DESCRIPTION='edu.wustl.catissuecore.domain.ClinicalStudyRegistration';
update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.EventEntry',NAME='edu.wustl.clinportal.domain.EventEntry' where DESCRIPTION='edu.wustl.catissuecore.domain.EventEntry';
update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.ClinicalStudyEvent',NAME='edu.wustl.clinportal.domain.ClinicalStudyEvent' where DESCRIPTION='edu.wustl.catissuecore.domain.ClinicalStudyEvent';
update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.StudyFormContext',NAME='edu.wustl.clinportal.domain.StudyFormContext' where DESCRIPTION='edu.wustl.catissuecore.domain.StudyFormContext';
update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.RecordEntry',NAME='edu.wustl.clinportal.domain.RecordEntry' where DESCRIPTION='edu.wustl.catissuecore.domain.RecordEntry';
update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.SpecimenProtocol', NAME='edu.wustl.clinportal.domain.SpecimenProtocol' where DESCRIPTION='edu.wustl.catissuecore.domain.SpecimenProtocol';
update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.User', NAME='edu.wustl.clinportal.domain.User' where DESCRIPTION='edu.wustl.catissuecore.domain.User';
update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.Department', NAME='edu.wustl.clinportal.domain.Department' where DESCRIPTION='edu.wustl.catissuecore.domain.Department';
update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.Password', NAME='edu.wustl.clinportal.domain.Password' where DESCRIPTION='edu.wustl.catissuecore.domain.Password';
update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.CancerResearchGroup', NAME='edu.wustl.clinportal.domain.CancerResearchGroup' where DESCRIPTION='edu.wustl.catissuecore.domain.CancerResearchGroup';
update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.Institution', NAME='edu.wustl.clinportal.domain.Institution' where DESCRIPTION='edu.wustl.catissuecore.domain.Institution';
update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.ClinicalStudy', NAME='edu.wustl.clinportal.domain.ClinicalStudy' where DESCRIPTION='edu.wustl.catissuecore.domain.ClinicalStudy';
update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.Participant', NAME='edu.wustl.clinportal.domain.Participant' where DESCRIPTION='edu.wustl.catissuecore.domain.Participant';
update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.ParticipantMedicalIdentifier', NAME='edu.wustl.clinportal.domain.ParticipantMedicalIdentifier' where DESCRIPTION='edu.wustl.catissuecore.domain.ParticipantMedicalIdentifier';
update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.Site', NAME='edu.wustl.clinportal.domain.Site' where DESCRIPTION='edu.wustl.catissuecore.domain.Site';
update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.Race', NAME='edu.wustl.clinportal.domain.Race' where DESCRIPTION='edu.wustl.catissuecore.domain.Race';
update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.ClinicalStudyConsentTier', NAME='edu.wustl.clinportal.domain.ClinicalStudyConsentTier' where NAME='edu.wustl.catissuecore.domain.ClinicalStudyConsentTier';
update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.ClinicalStudyConsentTierResponse', NAME='edu.wustl.clinportal.domain.ClinicalStudyConsentTierResponse' where NAME='edu.wustl.catissuecore.domain.ClinicalStudyConsentTierResponse';
update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.EventVisit',NAME='edu.wustl.clinportal.domain.EventVisit' where NAME='edu.wustl.clinportal.domain.EventEntry';
UPDATE DYEXTN_ROLE SET ASSOCIATION_TYPE = 'CONTAINTMENT' WHERE IDENTIFIER IN (select TARGET_ROLE_ID FROM DYEXTN_ASSOCIATION WHERE IDENTIFIER IN (select DE_ASSOCIATION_ID FROM INTRA_MODEL_ASSOCIATION WHERE ASSOCIATION_ID IN (select INTERMEDIATE_PATH FROM PATH WHERE FIRST_ENTITY_ID IN (SELECT IDENTIFIER FROM DYEXTN_ABSTRACT_METADATA WHERE NAME = 'edu.wustl.clinportal.domain.ClinicalStudy') AND LAST_ENTITY_ID IN (SELECT IDENTIFIER FROM DYEXTN_ABSTRACT_METADATA WHERE NAME = 'edu.wustl.clinportal.domain.ClinicalStudyEvent'))));
UPDATE DYEXTN_ROLE SET ASSOCIATION_TYPE = 'CONTAINTMENT' WHERE IDENTIFIER IN (select TARGET_ROLE_ID FROM DYEXTN_ASSOCIATION WHERE IDENTIFIER IN (select DE_ASSOCIATION_ID FROM INTRA_MODEL_ASSOCIATION WHERE ASSOCIATION_ID IN (select INTERMEDIATE_PATH FROM PATH WHERE FIRST_ENTITY_ID IN (SELECT IDENTIFIER FROM DYEXTN_ABSTRACT_METADATA WHERE NAME = 'edu.wustl.clinportal.domain.StudyFormContext') AND LAST_ENTITY_ID IN (SELECT IDENTIFIER FROM DYEXTN_ABSTRACT_METADATA WHERE NAME = 'edu.wustl.clinportal.domain.RecordEntry'))));
update dyextn_abstract_metadata set DESCRIPTION='edu.wustl.clinportal.domain.ResearchGroup',NAME='edu.wustl.clinportal.domain.ResearchGroup' where NAME='edu.wustl.clinportal.domain.CancerResearchGroup';

/*Bug #13563 Rename Cancer Research Group as Research Group*/
UPDATE CATISSUE_QUERY_TABLE_DATA SET DISPLAY_NAME = 'Research Group' where TABLE_ID=7;