/*Indexes for Participant*/
CREATE INDEX INDX_PARTICIPANT_LNAME ON CATISSUE_PARTICIPANT (LAST_NAME);
CREATE INDEX INDX_PARTICIPANT_FNAME ON CATISSUE_PARTICIPANT (FIRST_NAME);
CREATE INDEX INDX_PARTICIPANT_MNAME ON CATISSUE_PARTICIPANT (MIDDLE_NAME);
CREATE INDEX INDX_PARTICIPANT_BDATE ON CATISSUE_PARTICIPANT (BIRTH_DATE);
CREATE INDEX INDX_PARTICIPANT_DDATE ON CATISSUE_PARTICIPANT (DEATH_DATE);
CREATE INDEX INDX_PARTICIPANT_VSTATUS ON CATISSUE_PARTICIPANT (VITAL_STATUS);
CREATE INDEX INDX_PARTICIPANT_GENDER ON CATISSUE_PARTICIPANT (GENDER);
CREATE INDEX INDX_PARTICIPANT_GENOTYPE ON CATISSUE_PARTICIPANT (GENOTYPE);
CREATE INDEX INDX_RACE_NAME ON CATISSUE_RACE (RACE_NAME);
CREATE INDEX INDX_PARTICIPANT_ETHNICITY ON CATISSUE_PARTICIPANT (ETHNICITY);
/*CREATE INDEX INDX_PARTICIPANT_SSN ON CATISSUE_PARTICIPANT (SOCIAL_SECURITY_NUMBER);*/
CREATE INDEX INDX_PART_MEDICAL_RECNO ON CATISSUE_PART_MEDICAL_ID (MEDICAL_RECORD_NUMBER);


/* Indexes for Collection Protocol*/
CREATE INDEX INDX_USER_LNAME ON CATISSUE_USER (LAST_NAME);
CREATE INDEX INDX_USER_FNAME ON CATISSUE_USER (FIRST_NAME);
/*CREATE INDEX INDX_SPECIMEN_PROTOCOL_TITLE ON CATISSUE_SPECIMEN_PROTOCOL (TITLE);*/
CREATE INDEX INDX_SP_PR_SHORT_TITLE ON CATISSUE_SPECIMEN_PROTOCOL (SHORT_TITLE);
CREATE INDEX INDX_SP_PR_IRB_ID ON CATISSUE_SPECIMEN_PROTOCOL (IRB_IDENTIFIER);
CREATE INDEX INDX_SP_PR_START_DATE ON CATISSUE_SPECIMEN_PROTOCOL (START_DATE);
CREATE INDEX INDX_SP_PR_END_DATE ON CATISSUE_SPECIMEN_PROTOCOL (END_DATE);