
CREATE TABLE QUEUE
(
  CSM_ID           NUMBER,
  SOURCE_APP_NAME  VARCHAR2(25 BYTE),
  TARGET_APP_NAME  VARCHAR2(25 BYTE),
  NO_OF_TRIES      NUMBER,
  UPDATE_DATE      DATE,
  ID               NUMBER                       NOT NULL,
  IN_USE           CHAR(1 BYTE),
  ERR_MSG          VARCHAR2(250 BYTE)
);

ALTER TABLE QUEUE ADD (
  PRIMARY KEY (ID));
  
CREATE SEQUENCE queue_seq
START WITH 1
INCREMENT BY 1;

