
/*******CSM Upgrade from 3.1 to 3.2******/


ALTER TABLE CSM_PROTECTION_ELEMENT DROP COLUMN PROTECTION_ELEMENT_TYPE_ID;
ALTER TABLE CSM_PROTECTION_ELEMENT ADD PROTECTION_ELEMENT_TYPE VARCHAR(100);
ALTER TABLE CSM_PG_PE MODIFY  UPDATE_DATE DATE NULL;
ALTER TABLE CSM_PROTECTION_ELEMENT ADD ( CONSTRAINT UQ_PE_OBJ_ID_ATTR_APP_ID UNIQUE (PROTECTION_ELEMENT_NAME, ATTRIBUTE, APPLICATION_ID));


ALTER TABLE CSM_APPLICATION MODIFY APPLICATION_NAME varchar2(255) ;
ALTER TABLE CSM_GROUP MODIFY GROUP_NAME varchar2(255) ;

UPDATE csm_application SET csm_application.DECLARATIVE_FLAG='0';
UPDATE csm_pg_pe SET UPDATE_DATE=NULL;
