alter table DYEXTN_COLUMN_PROPERTIES drop column CONSTRAINT_NAME;

alter table DYEXTN_TABLE_PROPERTIES drop column CONSTRAINT_NAME;

alter table DYEXTN_CONSTRAINT_PROPERTIES drop column SRC_CONSTRAINT_NAME;

alter table DYEXTN_CONSTRAINT_PROPERTIES drop column TARGET_CONSTRAINT_NAME;

alter table DYEXTN_CONSTRAINT_PROPERTIES drop column SOURCE_ENTITY_KEY;

alter table DYEXTN_CONSTRAINT_PROPERTIES drop column TARGET_ENTITY_KEY;
