/*--- Clinportal CREATE Scripts Begin  ---*/


alter table CATISSUE_CLINICAL_STUDY drop foreign key FKE4B5E1FABC7298A9;
alter table CATISSUE_STUDY_COORDINATORS drop foreign key FK39C921682206F20F;
alter table CATISSUE_STUDY_COORDINATORS drop foreign key FK39C921689D75BF84;
alter table CATISSUE_CLINICAL_STUDY_EVENT drop foreign key FKE054953483880B1D;
alter table CATISUE_CLIN_STUDY_RECORD_NTRY drop foreign key FK2BE470A38E43C0C7;
alter table CATISSUE_STUDY_FORM_CONTEXT drop foreign key FK24923AE633052182;
alter table CATISSUE_CLINICAL_STUDY_REG drop foreign key FK3D3CBDAE87E5ADC7;
alter table CATISSUE_CLINICAL_STUDY_REG drop foreign key FK3D3CBDAE83880B1D;
alter table CATISUE_CLIN_STUDY_RECORD_NTRY drop foreign key FK2BE470A3E2BA39DE;
alter table CATISUE_CLIN_STUDY_RECORD_NTRY drop foreign key FK2BE470A3DDFAC4E7;



drop table if exists CATISSUE_CLINICAL_STUDY_REG;
drop table if exists CATISSUE_CLINICAL_STUDY;
drop table if exists CATISSUE_STUDY_COORDINATORS;
drop table if exists CATISSUE_CLINICAL_STUDY_EVENT;
drop table if exists CATISUE_CLIN_STUDY_RECORD_NTRY;
drop table if exists CATISSUE_STUDY_FORM_CONTEXT;
drop table if exists CATISUE_CLIN_STUDY_RECORD_NTRY;
drop table if exists CATISSUE_EVENT_ENTRY;


create table CATISSUE_EVENT_ENTRY (
   IDENTIFIER bigint not null auto_increment,
   ENCOUNTER_DATE date,
   ACTIVITY_STATUS varchar(10),
   CLINICAL_STUDY_EVENT_ID bigint,
   CLINICAL_STUDY_REG_ID bigint,
    ENTRY_NUMBER integer,
   primary key (IDENTIFIER)
);

create table CATISUE_CLIN_STUDY_RECORD_NTRY (
   IDENTIFIER bigint not null auto_increment,
   EVENT_ENTRY_ID bigint,   
   ACTIVITY_STATUS varchar2(50),
   STUDY_FORM_CONTXT_ID bigint,  
   primary key (IDENTIFIER)
);

create table CATISSUE_CLINICAL_STUDY_EVENT (
   IDENTIFIER bigint not null auto_increment,
   CLINICAL_STUDY_ID bigint,
   COLLECTION_POINT_LABEL varchar(255),
   EVENT_POINT double precision,
   NO_OF_ENTRIES integer,
   ACTIVITY_STATUS varchar(10),
   IS_INFINITE_ENTRY bit,
   primary key (IDENTIFIER)
);

create table CATISSUE_CLINICAL_STUDY_REG (
   IDENTIFIER bigint not null auto_increment,
   CLINICAL_STUDY_PARTICIPANT_ID varchar(255),
   REGISTRATION_DATE date,
   PARTICIPANT_ID bigint,
   ACTIVITY_STATUS varchar(50),
   CLINICAL_STUDY_ID bigint,
   primary key (IDENTIFIER)
);

create table CATISSUE_CLINICAL_STUDY (
   IDENTIFIER bigint not null,
   primary key (IDENTIFIER)
);

create table CATISSUE_STUDY_COORDINATORS (
   CLINICAL_STUDY_ID bigint not null,
   USER_ID bigint not null,
   primary key (CLINICAL_STUDY_ID, USER_ID)
);
create table CATISSUE_STUDY_FORM_CONTEXT (
   IDENTIFIER bigint not null auto_increment,
   CLINICAL_STUDY_EVENT_ID bigint,
   STUDY_FORM_LABEL varchar(255),
   CONTAINER_ID bigint,
   ACTIVITY_STATUS varchar(10),
   CAN_HAVE_MULTIPLE_RECORDS number(1,0),
   primary key (IDENTIFIER)
);

alter table CATISSUE_CLINICAL_STUDY add index FKE4B5E1FABC7298A9 (IDENTIFIER), add constraint FKE4B5E1FABC7298A9 foreign key (IDENTIFIER) references CATISSUE_SPECIMEN_PROTOCOL (IDENTIFIER);
alter table CATISSUE_STUDY_COORDINATORS add index FK39C921682206F20F (USER_ID), add constraint FK39C921682206F20F foreign key (USER_ID) references CATISSUE_USER (IDENTIFIER);
alter table CATISSUE_STUDY_COORDINATORS add index FK39C921689D75BF84 (CLINICAL_STUDY_ID), add constraint FK39C921689D75BF84 foreign key (CLINICAL_STUDY_ID) references CATISSUE_CLINICAL_STUDY (IDENTIFIER);
alter table CATISSUE_CLINICAL_STUDY_EVENT add index FKE054953483880B1D (CLINICAL_STUDY_ID), add constraint FKE054953483880B1D foreign key (CLINICAL_STUDY_ID) references CATISSUE_CLINICAL_STUDY (IDENTIFIER);
alter table CATISSUE_STUDY_FORM_CONTEXT add index FK24923AE633052182 (CLINICAL_STUDY_EVENT_ID), add constraint FK24923AE633052182 foreign key (CLINICAL_STUDY_EVENT_ID) references CATISSUE_CLINICAL_STUDY_EVENT (IDENTIFIER);
alter table CATISUE_CLIN_STUDY_RECORD_NTRY add index FK2BE470A3DDFAC4E7 (STUDY_FORM_CONTXT_ID), add constraint FK2BE470A3DDFAC4E7 foreign key (STUDY_FORM_CONTXT_ID) references CATISSUE_STUDY_FORM_CONTEXT (IDENTIFIER);
alter table CATISSUE_CLINICAL_STUDY_REG add index FK3D3CBDAE87E5ADC7 (PARTICIPANT_ID), add constraint FK3D3CBDAE87E5ADC7 foreign key (PARTICIPANT_ID) references CATISSUE_PARTICIPANT (IDENTIFIER);
alter table CATISSUE_CLINICAL_STUDY_REG add index FK3D3CBDAE83880B1D (CLINICAL_STUDY_ID), add constraint FK3D3CBDAE83880B1D foreign key (CLINICAL_STUDY_ID) references CATISSUE_CLINICAL_STUDY (IDENTIFIER);
alter table CATISUE_CLIN_STUDY_RECORD_NTRY add index FK2BE470A3E2BA39DE (EVENT_ENTRY_ID), add constraint FK2BE470A3E2BA39DE foreign key (EVENT_ENTRY_ID) references CATISSUE_EVENT_ENTRY (IDENTIFIER);
alter table CATISSUE_EVENT_ENTRY add index FK90328AD133052182 (CLINICAL_STUDY_EVENT_ID), add constraint FK90328AD133052182 foreign key (CLINICAL_STUDY_EVENT_ID) references CATISSUE_CLINICAL_STUDY_EVENT (IDENTIFIER);
alter table CATISSUE_EVENT_ENTRY add index FK90328AD12BAE9DC8 (CLINICAL_STUDY_REG_ID), add constraint FK90328AD12BAE9DC8 foreign key (CLINICAL_STUDY_REG_ID) references CATISSUE_CLINICAL_STUDY_REG (IDENTIFIER);


/*--- Clinportal CREATE Scripts End ---*/